name: Compile

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
  
    strategy:
      matrix:
        version: ["1.11"]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Environments
        run: |
          echo "SM_VERSION=${{ matrix.version }}" >> $GITHUB_ENV
      
      - name: Install
        run: |
          bash scripts/install.sh
      
      - name: Compile
        run: |
          cd build/addons/sourcemod/scripting
          ./spcomp -E randomizer.sp -o ../plugins/randomizer.smx